/** ESG Analyst perspective panel (Phase 4 Stage 11a output renderer).
 *
 * Renders the rich analyst-grade output: KPI table with peer quartiles,
 * confidence bounds on every ₹ estimate, double materiality split, TCFD
 * scenarios, SDG sub-goals, audit trail, framework citations.
 *
 * Pair with the existing KnowMoreSheet or mount stand-alone as a tab
 * inside ArticleDetailSheet. All fields degrade gracefully — missing
 * blocks are omitted (no empty placeholders).
 */

import type {
  EsgAnalystConfidenceBound,
  EsgAnalystPerspective,
  EsgAnalystFrameworkCitation,
  EsgAnalystKpi,
  EsgAnalystSdgTarget,
} from "@/types/perspectives";

interface ESGAnalystPanelProps {
  data: EsgAnalystPerspective;
  companyName?: string;
}

export function ESGAnalystPanel({ data, companyName }: ESGAnalystPanelProps) {
  return (
    <div className="space-y-6 text-sm text-gray-800">
      {/* Headline */}
      <header className="border-l-4 border-indigo-600 pl-4">
        <h2 className="text-lg font-semibold text-gray-900">{data.headline}</h2>
        {companyName && (
          <p className="text-xs text-gray-500 mt-1">ESG Analyst view · {companyName}</p>
        )}
        {data.generated_by && (
          <p className="text-[11px] text-gray-400 mt-0.5">
            Generated by <code>{data.generated_by}</code>
          </p>
        )}
      </header>

      {/* KPI table */}
      {data.kpi_table.length > 0 && <KpiTable kpis={data.kpi_table} />}

      {/* Confidence bounds */}
      {data.confidence_bounds.length > 0 && (
        <ConfidenceBounds bounds={data.confidence_bounds} />
      )}

      {/* Double materiality */}
      {(data.double_materiality.financial_impact || data.double_materiality.impact_on_world) && (
        <DoubleMateriality dm={data.double_materiality} />
      )}

      {/* TCFD scenarios */}
      {Object.values(data.tcfd_scenarios).some(Boolean) && (
        <TcfdScenarios scenarios={data.tcfd_scenarios} />
      )}

      {/* SDG targets */}
      {data.sdg_targets.length > 0 && <SdgTargets targets={data.sdg_targets} />}

      {/* Framework citations */}
      {data.framework_citations.length > 0 && (
        <FrameworkCitations cites={data.framework_citations} />
      )}

      {/* Audit trail */}
      {data.audit_trail.length > 0 && (
        <details className="bg-gray-50 border border-gray-200 rounded p-3">
          <summary className="cursor-pointer text-xs font-semibold text-gray-700">
            Audit trail ({data.audit_trail.length})
          </summary>
          <ul className="mt-2 space-y-2">
            {data.audit_trail.map((entry, i) => (
              <li key={i} className="text-xs">
                <div className="font-medium text-gray-800">{entry.claim}</div>
                <div className="text-gray-600 mt-0.5">{entry.derivation}</div>
                {entry.sources?.length > 0 && (
                  <div className="text-gray-400 mt-0.5">
                    sources: {entry.sources.join(", ")}
                  </div>
                )}
              </li>
            ))}
          </ul>
        </details>
      )}

      {/* Warnings (non-fatal, informational) */}
      {data.warnings.length > 0 && (
        <div className="text-[11px] text-amber-600 border-l-2 border-amber-300 pl-2">
          {data.warnings.map((w, i) => (
            <div key={i}>⚠ {w}</div>
          ))}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function KpiTable({ kpis }: { kpis: EsgAnalystKpi[] }) {
  return (
    <section>
      <h3 className="text-sm font-semibold text-gray-700 mb-2">Quantitative KPIs</h3>
      <div className="overflow-x-auto">
        <table className="w-full text-xs border-collapse">
          <thead>
            <tr className="bg-gray-100 text-left">
              <th className="py-1.5 px-2 font-semibold">KPI</th>
              <th className="py-1.5 px-2 font-semibold">Value</th>
              <th className="py-1.5 px-2 font-semibold">Unit</th>
              <th className="py-1.5 px-2 font-semibold">Peer quartile</th>
              <th className="py-1.5 px-2 font-semibold">Source</th>
            </tr>
          </thead>
          <tbody>
            {kpis.map((k, i) => (
              <tr key={i} className="border-t border-gray-200">
                <td className="py-1.5 px-2 font-medium">{k.kpi_name}</td>
                <td className="py-1.5 px-2">{k.company_value}</td>
                <td className="py-1.5 px-2 text-gray-600">{k.unit || "—"}</td>
                <td className="py-1.5 px-2 text-gray-600">{k.peer_quartile || "—"}</td>
                <td className="py-1.5 px-2 text-gray-500 text-[11px]">{k.data_source || "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function ConfidenceBounds({ bounds }: { bounds: EsgAnalystConfidenceBound[] }) {
  return (
    <section>
      <h3 className="text-sm font-semibold text-gray-700 mb-2">
        Confidence bounds on ₹ estimates
      </h3>
      <ul className="space-y-2">
        {bounds.map((b, i) => (
          <li key={i} className="bg-white border border-gray-200 rounded p-2 text-xs">
            <div className="flex items-center gap-2">
              <span className="font-semibold text-gray-900">{b.figure}</span>
              <SourceTagPill sourceType={b.source_type} />
              {b.confidence && <ConfidencePill level={b.confidence} />}
            </div>
            {(b.beta_range || b.lag || b.functional_form) && (
              <div className="mt-1 text-gray-600 font-mono text-[11px]">
                {b.beta_range && <span>β {b.beta_range}</span>}
                {b.lag && <span className="ml-2">· lag {b.lag}</span>}
                {b.functional_form && <span className="ml-2">· {b.functional_form}</span>}
              </div>
            )}
            {b.rationale && <div className="mt-1 text-gray-600">{b.rationale}</div>}
          </li>
        ))}
      </ul>
    </section>
  );
}

function DoubleMateriality({
  dm,
}: {
  dm: { financial_impact?: string; impact_on_world?: string };
}) {
  return (
    <section>
      <h3 className="text-sm font-semibold text-gray-700 mb-2">Double materiality</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {dm.financial_impact && (
          <div className="bg-blue-50 border border-blue-100 rounded p-3">
            <div className="text-[11px] uppercase text-blue-700 font-semibold mb-1">
              Financial impact on {"{company}"}
            </div>
            <div className="text-xs text-gray-800">{dm.financial_impact}</div>
          </div>
        )}
        {dm.impact_on_world && (
          <div className="bg-emerald-50 border border-emerald-100 rounded p-3">
            <div className="text-[11px] uppercase text-emerald-700 font-semibold mb-1">
              Impact on world
            </div>
            <div className="text-xs text-gray-800">{dm.impact_on_world}</div>
          </div>
        )}
      </div>
    </section>
  );
}

function TcfdScenarios({
  scenarios,
}: {
  scenarios: { "1_5c"?: string; "2c"?: string; "4c"?: string };
}) {
  const paths: { label: string; key: keyof typeof scenarios; color: string }[] = [
    { label: "1.5°C", key: "1_5c", color: "text-emerald-700 border-emerald-300" },
    { label: "2°C", key: "2c", color: "text-amber-700 border-amber-300" },
    { label: "4°C", key: "4c", color: "text-red-700 border-red-300" },
  ];
  return (
    <section>
      <h3 className="text-sm font-semibold text-gray-700 mb-2">TCFD scenarios</h3>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        {paths.map(({ label, key, color }) =>
          scenarios[key] ? (
            <div key={key} className={`border-l-2 pl-3 ${color}`}>
              <div className="text-[11px] uppercase font-semibold">{label}</div>
              <div className="text-xs text-gray-700 mt-1">{scenarios[key]}</div>
            </div>
          ) : null
        )}
      </div>
    </section>
  );
}

function SdgTargets({ targets }: { targets: EsgAnalystSdgTarget[] }) {
  return (
    <section>
      <h3 className="text-sm font-semibold text-gray-700 mb-2">SDG targets triggered</h3>
      <ul className="flex flex-wrap gap-2">
        {targets.map((t, i) => (
          <li
            key={i}
            className="bg-white border border-gray-300 rounded px-2 py-1 text-xs"
            title={t.rationale || ""}
          >
            <span className="font-semibold text-indigo-700">SDG {t.code}</span>
            <span className="ml-1 text-gray-700">{t.title}</span>
            {t.applicability && (
              <span className="ml-1 text-[10px] text-gray-500 uppercase">
                ({t.applicability})
              </span>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}

function FrameworkCitations({ cites }: { cites: EsgAnalystFrameworkCitation[] }) {
  return (
    <section>
      <h3 className="text-sm font-semibold text-gray-700 mb-2">Framework citations</h3>
      <ul className="space-y-1.5">
        {cites.map((c, i) => (
          <li key={i} className="text-xs">
            <code className="bg-gray-100 px-1.5 py-0.5 rounded font-semibold text-indigo-800">
              {c.code}
            </code>
            <span className="ml-2 text-gray-700">{c.rationale}</span>
            {c.deadline && (
              <span className="ml-2 text-[10px] text-amber-700 font-medium">
                deadline: {c.deadline}
              </span>
            )}
            {c.region && (
              <span className="ml-2 text-[10px] text-gray-500">· {c.region}</span>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}

function SourceTagPill({ sourceType }: { sourceType: string }) {
  const isArticle = sourceType.includes("article");
  const style = isArticle
    ? "bg-blue-100 text-blue-800"
    : "bg-gray-100 text-gray-700";
  const label = isArticle ? "from article" : "engine estimate";
  return (
    <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium uppercase ${style}`}>
      {label}
    </span>
  );
}

function ConfidencePill({ level }: { level: string }) {
  const map: Record<string, string> = {
    high: "bg-emerald-100 text-emerald-800",
    medium: "bg-amber-100 text-amber-800",
    low: "bg-red-100 text-red-800",
  };
  const style = map[level.toLowerCase()] || "bg-gray-100 text-gray-700";
  return (
    <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium uppercase ${style}`}>
      {level}
    </span>
  );
}
