"""Phase 11C+ — Regenerate the email logo assets from SNOWKAP_logo.png.

Source of truth for Phase 11+ is `SNOWKAP_logo.png` at the repo root (a
hand-exported PNG from Illustrator, since the PyMuPDF PDF path produced
letterforms with visible fringing). Run this whenever the brand mark
changes, then commit the regenerated `client/public/assets/*.png` and
`engine/output/email_assets.py`.

Emits:
    client/public/assets/snowkap-logo-email.png      (480x76 @ 2x retina, dark bg) → CID source
    client/public/assets/snowkap-logo.png            (560x~89, dark bg)
    client/public/assets/snowkap-logo-small.png      (336x~53, dark bg)
    client/public/assets/snowkap-logo-transparent.png (480x~76, no bg)
    engine/output/email_assets.py                    (regenerated base64)

Run:
    python scripts/rasterise_sk_logo.py

The old PyMuPDF (fitz) / cairo-based PDF path was removed in Phase 11C
because the hand-exported PNG preserves anti-aliasing on the SNOWKAP 'A'
and 'P' terminals that the PDF renderer was fringing.
"""

from __future__ import annotations

import argparse
import base64
import sys
import textwrap
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
BG_DARK = (15, 23, 42)  # #0F172A — matches BRAND_DARK in newsletter_renderer


def _composite_and_save(im, target_width: int, dest: Path, on_dark: bool) -> None:
    from PIL import Image

    w, _h = im.size
    scale = target_width / w
    new_size = (target_width, int(round(im.size[1] * scale)))
    resized = im.resize(new_size, Image.LANCZOS)
    if on_dark:
        canvas = Image.new("RGB", new_size, BG_DARK)
        canvas.paste(resized, mask=resized.split()[3])
        canvas.save(dest, format="PNG", optimize=True)
    else:
        resized.save(dest, format="PNG", optimize=True)
    print(f"  wrote {dest} ({dest.stat().st_size:,} bytes) {new_size[0]}x{new_size[1]}")


def _regenerate_email_assets_module(email_png: Path, out_py: Path) -> None:
    b64 = base64.b64encode(email_png.read_bytes()).decode("ascii")
    wrapped = "\n".join('    "' + line + '"' for line in textwrap.wrap(b64, 72))
    body = f'''"""Inline email assets — base64-encoded PNG logo for Resend CID attachments.

Regenerated by `scripts/rasterise_sk_logo.py` from
`client/public/assets/snowkap-logo-email.png` (composited on #0F172A so the
email header looks seamless across every client including Outlook Desktop).

Referenced from `engine/output/newsletter_renderer.py::_brand_header_dark()`
via `<img src="cid:snowkap-logo">`, wired to Resend's `attachments` param.
"""
from __future__ import annotations

import base64

SNOWKAP_LOGO_CONTENT_ID = "snowkap-logo"
SNOWKAP_LOGO_FILENAME = "snowkap-logo.png"
SNOWKAP_LOGO_MIME = "image/png"


# base64-encoded PNG bytes. Wrapped at 72 chars per line for diff-friendliness;
# the value is one continuous string at runtime.
SNOWKAP_LOGO_BASE64 = (
{wrapped}
)


def logo_bytes() -> bytes:
    """Return the raw PNG bytes (decoded from SNOWKAP_LOGO_BASE64)."""
    return base64.b64decode(SNOWKAP_LOGO_BASE64)


def logo_attachment() -> dict:
    """Return a Resend-compatible inline attachment dict for the logo.

    Resend expects: {{"content": <base64 str>, "filename": str, "content_id": str}}
    The content_id must match the `cid:` reference used by the <img> tag in
    the rendered HTML (see `newsletter_renderer._brand_header_dark`).
    """
    return {{
        "content": SNOWKAP_LOGO_BASE64,
        "filename": SNOWKAP_LOGO_FILENAME,
        "content_id": SNOWKAP_LOGO_CONTENT_ID,
    }}
'''
    out_py.write_text(body, encoding="utf-8")
    print(f"  wrote {out_py} ({out_py.stat().st_size:,} bytes, b64 length: {len(b64)})")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        default=str(_ROOT / "SNOWKAP_logo.png"),
        help="Source PNG (RGBA preferred). Defaults to SNOWKAP_logo.png at repo root.",
    )
    args = parser.parse_args(argv)

    src = Path(args.source)
    if not src.exists():
        print(f"error: source PNG not found: {src}", file=sys.stderr)
        return 2

    try:
        from PIL import Image
    except ImportError:
        print("error: Pillow not installed. Run `pip install Pillow`.", file=sys.stderr)
        return 3

    im = Image.open(src).convert("RGBA")
    print(f"source: {src} ({im.size[0]}x{im.size[1]}, {im.mode})")

    out_dir = _ROOT / "client" / "public" / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)

    _composite_and_save(im, 480, out_dir / "snowkap-logo-email.png", on_dark=True)
    _composite_and_save(im, 560, out_dir / "snowkap-logo.png", on_dark=True)
    _composite_and_save(im, 336, out_dir / "snowkap-logo-small.png", on_dark=True)
    _composite_and_save(im, 480, out_dir / "snowkap-logo-transparent.png", on_dark=False)

    _regenerate_email_assets_module(
        out_dir / "snowkap-logo-email.png",
        _ROOT / "engine" / "output" / "email_assets.py",
    )

    print("done. Commit the PNGs + email_assets.py and the next email send uses them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
